# Generated by Django 5.2.11 on 2026-02-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.product'),
        ),
    ]
